<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['code' => 'AX', 'name' => 'جزر أولان'],
            ['code' => 'AL', 'name' => 'ألبانيا'],
            ['code' => 'DZ', 'name' => 'الجزائر'],
            ['code' => 'AS', 'name' => 'ساموا الأمريكية'],
            ['code' => 'AD', 'name' => 'أندورا'],
            ['code' => 'AO', 'name' => 'أنغولا'],
            ['code' => 'AI', 'name' => 'أنغويلا'],
            ['code' => 'AQ', 'name' => 'أنتاركتيكا'],
            ['code' => 'AG', 'name' => 'أنتيغوا وبربودا'],
            ['code' => 'AR', 'name' => 'الأرجنتين'],
            ['code' => 'AM', 'name' => 'أرمينيا'],
            ['code' => 'AW', 'name' => 'آروبا'],
            ['code' => 'AU', 'name' => 'أستراليا'],
            ['code' => 'AT', 'name' => 'النمسا'],
            ['code' => 'AZ', 'name' => 'أذربيجان'],
            ['code' => 'BS', 'name' => 'الباهاما'],
            ['code' => 'BH', 'name' => 'البحرين'],
            ['code' => 'BD', 'name' => 'بنجلاديش'],
            ['code' => 'BB', 'name' => 'بربادوس'],
            ['code' => 'BY', 'name' => 'روسيا البيضاء'],
            ['code' => 'BE', 'name' => 'بلجيكا'],
            ['code' => 'BZ', 'name' => 'بليز'],
            ['code' => 'BJ', 'name' => 'بنين'],
            ['code' => 'BM', 'name' => 'برمودا'],
            ['code' => 'BT', 'name' => 'بوتان'],
            ['code' => 'BO', 'name' => 'بوليفيا'],
            ['code' => 'BQ', 'name' => 'هولندا الكاريبية'],
            ['code' => 'BA', 'name' => 'البوسنة والهرسك'],
            ['code' => 'BW', 'name' => 'بتسوانا'],
            ['code' => 'BV', 'name' => 'جزيرة بوفيه'],
            ['code' => 'BR', 'name' => 'البرازيل'],
            ['code' => 'IO', 'name' => 'الإقليم البريطاني في المحيط الهندي'],
            ['code' => 'BN', 'name' => 'بروناي'],
            ['code' => 'BG', 'name' => 'بلغاريا'],
            ['code' => 'BF', 'name' => 'بوركينا فاسو'],
            ['code' => 'BI', 'name' => 'بوروندي'],
            ['code' => 'KH', 'name' => 'كمبوديا'],
            ['code' => 'CM', 'name' => 'الكاميرون'],
            ['code' => 'CA', 'name' => 'كندا'],
            ['code' => 'CV', 'name' => 'الرأس الأخضر'],
            ['code' => 'KY', 'name' => 'جزر الكايمن'],
            ['code' => 'CF', 'name' => 'جمهورية أفريقيا الوسطى'],
            ['code' => 'TD', 'name' => 'تشاد'],
            ['code' => 'CL', 'name' => 'شيلي'],
            ['code' => 'CN', 'name' => 'الصين'],
            ['code' => 'CX', 'name' => 'جزيرة الكريسماس'],
            ['code' => 'CC', 'name' => 'جزر كوكوس'],
            ['code' => 'CO', 'name' => 'كولومبيا'],
            ['code' => 'KM', 'name' => 'جزر القمر'],
            ['code' => 'CG', 'name' => 'الكونغو - برازافيل'],
            ['code' => 'CD', 'name' => 'الكونغو - كينشاسا'],
            ['code' => 'CK', 'name' => 'جزر كوك'],
            ['code' => 'CR', 'name' => 'كوستاريكا'],
            ['code' => 'CI', 'name' => 'ساحل العاج'],
            ['code' => 'HR', 'name' => 'كرواتيا'],
            ['code' => 'CU', 'name' => 'كوبا'],
            ['code' => 'CW', 'name' => 'كوراساو'],
            ['code' => 'CY', 'name' => 'قبرص'],
            ['code' => 'CZ', 'name' => 'جمهورية التشيك'],
            ['code' => 'DK', 'name' => 'الدانمرك'],
            ['code' => 'DJ', 'name' => 'جيبوتي'],
            ['code' => 'DM', 'name' => 'دومينيكا'],
            ['code' => 'DO', 'name' => 'جمهورية الدومينيك'],
            ['code' => 'EC', 'name' => 'الإكوادور'],
            ['code' => 'EG', 'name' => 'مصر'],
            ['code' => 'SV', 'name' => 'السلفادور'],
            ['code' => 'GQ', 'name' => 'غينيا الإستوائية'],
            ['code' => 'ER', 'name' => 'أريتريا'],
            ['code' => 'EE', 'name' => 'أستونيا'],
            ['code' => 'ET', 'name' => 'إثيوبيا'],
            ['code' => 'FK', 'name' => 'جزر فوكلاند'],
            ['code' => 'FO', 'name' => 'جزر فارو'],
            ['code' => 'FJ', 'name' => 'فيجي'],
            ['code' => 'FI', 'name' => 'فنلندا'],
            ['code' => 'FR', 'name' => 'فرنسا'],
            ['code' => 'GF', 'name' => 'غويانا الفرنسية'],
            ['code' => 'PF', 'name' => 'بولينيزيا الفرنسية'],
            ['code' => 'TF', 'name' => 'المقاطعات الجنوبية الفرنسية'],
            ['code' => 'GA', 'name' => 'الجابون'],
            ['code' => 'GM', 'name' => 'غامبيا'],
            ['code' => 'GE', 'name' => 'جورجيا'],
            ['code' => 'DE', 'name' => 'ألمانيا'],
            ['code' => 'GH', 'name' => 'غانا'],
            ['code' => 'GI', 'name' => 'جبل طارق'],
            ['code' => 'GR', 'name' => 'اليونان'],
            ['code' => 'GL', 'name' => 'غرينلاند'],
            ['code' => 'GD', 'name' => 'غرينادا'],
            ['code' => 'GP', 'name' => 'جوادلوب'],
            ['code' => 'GU', 'name' => 'غوام'],
            ['code' => 'GT', 'name' => 'غواتيمالا'],
            ['code' => 'GG', 'name' => 'غيرنزي'],
            ['code' => 'GN', 'name' => 'غينيا'],
            ['code' => 'GW', 'name' => 'غينيا بيساو'],
            ['code' => 'GY', 'name' => 'غيانا'],
            ['code' => 'HT', 'name' => 'هايتي'],
            ['code' => 'HM', 'name' => 'جزيرة هيرد وجزر ماكدونالد'],
            ['code' => 'VA', 'name' => 'الفاتيكان'],
            ['code' => 'HN', 'name' => 'هندوراس'],
            ['code' => 'HK', 'name' => 'هونغ كونغ'],
            ['code' => 'HU', 'name' => 'هنغاريا'],
            ['code' => 'IS', 'name' => 'أيسلندا'],
            ['code' => 'IN', 'name' => 'الهند'],
            ['code' => 'ID', 'name' => 'أندونيسيا'],
            ['code' => 'IR', 'name' => 'ایران'],
            ['code' => 'IQ', 'name' => 'العراق'],
            ['code' => 'IE', 'name' => 'أيرلندا'],
            ['code' => 'IM', 'name' => 'جزيرة مان'],
            ['code' => 'IL', 'name' => 'الأراضي الفلسطينية المحتلة'],
            ['code' => 'IT', 'name' => 'إيطاليا'],
            ['code' => 'JM', 'name' => 'جامايكا'],
            ['code' => 'JP', 'name' => 'اليابان'],
            ['code' => 'JE', 'name' => 'جيرسي'],
            ['code' => 'JO', 'name' => 'الأردن'],
            ['code' => 'KZ', 'name' => 'كازاخستان'],
            ['code' => 'KE', 'name' => 'كينيا'],
            ['code' => 'KI', 'name' => 'كيريباتي'],
            ['code' => 'KP', 'name' => 'كوريا الشمالية'],
            ['code' => 'KR', 'name' => 'كوريا الجنوبية'],
            ['code' => 'KW', 'name' => 'الكويت'],
            ['code' => 'KG', 'name' => 'قرغيزستان'],
            ['code' => 'LA', 'name' => 'لاوس'],
            ['code' => 'LV', 'name' => 'لاتفيا'],
            ['code' => 'LB', 'name' => 'لبنان'],
            ['code' => 'LS', 'name' => 'ليسوتو'],
            ['code' => 'LR', 'name' => 'ليبيريا'],
            ['code' => 'LY', 'name' => 'ليبيا'],
            ['code' => 'LI', 'name' => 'ليختنشتاين'],
            ['code' => 'LT', 'name' => 'ليتوانيا'],
            ['code' => 'LU', 'name' => 'لوكسمبورغ'],
            ['code' => 'MO', 'name' => 'مكاو'],
            ['code' => 'MK', 'name' => 'مقدونيا'],
            ['code' => 'MG', 'name' => 'مدغشقر'],
            ['code' => 'MW', 'name' => 'ملاوي'],
            ['code' => 'MY', 'name' => 'ماليزيا'],
            ['code' => 'MV', 'name' => 'جزر المالديف'],
            ['code' => 'ML', 'name' => 'مالي'],
            ['code' => 'MT', 'name' => 'مالطا'],
            ['code' => 'MH', 'name' => 'جزر المارشال'],
            ['code' => 'MQ', 'name' => 'مارتينيك'],
            ['code' => 'MR', 'name' => 'موريتانيا'],
            ['code' => 'MU', 'name' => 'موريشيوس'],
            ['code' => 'YT', 'name' => 'مايوت'],
            ['code' => 'MX', 'name' => 'المكسيك'],
            ['code' => 'FM', 'name' => 'ميكرونيزيا'],
            ['code' => 'MD', 'name' => 'مولدافيا'],
            ['code' => 'MC', 'name' => 'موناكو'],
            ['code' => 'MN', 'name' => 'منغوليا'],
            ['code' => 'ME', 'name' => 'الجبل الأسود'],
            ['code' => 'MS', 'name' => 'مونتسرات'],
            ['code' => 'MA', 'name' => 'المغرب'],
            ['code' => 'MZ', 'name' => 'موزمبيق'],
            ['code' => 'MM', 'name' => 'ميانمار -بورما'],
            ['code' => 'NA', 'name' => 'ناميبيا'],
            ['code' => 'NR', 'name' => 'ناورو'],
            ['code' => 'NP', 'name' => 'نيبال'],
            ['code' => 'NL', 'name' => 'هولندا'],
            ['code' => 'NC', 'name' => 'كاليدونيا الجديدة'],
            ['code' => 'NZ', 'name' => 'نيوزيلاندا'],
            ['code' => 'NI', 'name' => 'نيكاراغوا'],
            ['code' => 'NE', 'name' => 'النيجر'],
            ['code' => 'NG', 'name' => 'نيجيريا'],
            ['code' => 'NU', 'name' => 'نيوي'],
            ['code' => 'NF', 'name' => 'جزيرة نورفوك'],
            ['code' => 'MP', 'name' => 'جزر ماريانا الشمالية'],
            ['code' => 'NO', 'name' => 'النرويج'],
            ['code' => 'OM', 'name' => 'عُمان'],
            ['code' => 'PK', 'name' => 'باكستان'],
            ['code' => 'PW', 'name' => 'بالاو'],
            ['code' => 'PS', 'name' => 'فلسطين'],
            ['code' => 'PA', 'name' => 'بنما'],
            ['code' => 'PG', 'name' => 'بابوا غينيا الجديدة'],
            ['code' => 'PY', 'name' => 'باراغواي'],
            ['code' => 'PE', 'name' => 'بيرو'],
            ['code' => 'PH', 'name' => 'الفلبين'],
            ['code' => 'PN', 'name' => 'جزر بيتكيرن'],
            ['code' => 'PL', 'name' => 'بولندا'],
            ['code' => 'PT', 'name' => 'البرتغال'],
            ['code' => 'PR', 'name' => 'بورتوريكو'],
            ['code' => 'QA', 'name' => 'قطر'],
            ['code' => 'RE', 'name' => 'روينيون'],
            ['code' => 'RO', 'name' => 'رومانيا'],
            ['code' => 'RU', 'name' => 'روسيا'],
            ['code' => 'RW', 'name' => 'رواندا'],
            ['code' => 'BL', 'name' => 'سان بارتليمي'],
            ['code' => 'SH', 'name' => 'سانت هيلنا'],
            ['code' => 'KN', 'name' => 'سانت كيتس ونيفيس'],
            ['code' => 'LC', 'name' => 'سانت لوسيا'],
            ['code' => 'MF', 'name' => 'سانت مارتن'],
            ['code' => 'PM', 'name' => 'سانت بيير وميكولون'],
            ['code' => 'VC', 'name' => 'سانت فنسنت وغرنادين'],
            ['code' => 'WS', 'name' => 'ساموا'],
            ['code' => 'SM', 'name' => 'سان مارينو'],
            ['code' => 'ST', 'name' => 'ساو تومي وبرينسيبي'],
            ['code' => 'SA', 'name' => 'المملكة العربية السعودية'],
            ['code' => 'SN', 'name' => 'السنغال'],
            ['code' => 'RS', 'name' => 'صربيا'],
            ['code' => 'SC', 'name' => 'سيشل'],
            ['code' => 'SL', 'name' => 'سيراليون'],
            ['code' => 'SG', 'name' => 'سنغافورة'],
            ['code' => 'SX', 'name' => 'سينت مارتن'],
            ['code' => 'SK', 'name' => 'سلوفاكيا'],
            ['code' => 'SI', 'name' => 'سلوفينيا'],
            ['code' => 'SB', 'name' => 'جزر سليمان'],
            ['code' => 'SO', 'name' => 'الصومال'],
            ['code' => 'ZA', 'name' => 'جنوب أفريقيا'],
            ['code' => 'GS', 'name' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'],
            ['code' => 'SS', 'name' => 'جنوب السودان'],
            ['code' => 'ES', 'name' => 'إسبانيا'],
            ['code' => 'LK', 'name' => 'سريلانكا'],
            ['code' => 'SD', 'name' => 'السودان'],
            ['code' => 'SR', 'name' => 'سورينام'],
            ['code' => 'SJ', 'name' => 'سفالبارد وجان مايان'],
            ['code' => 'SZ', 'name' => 'سوازيلاند'],
            ['code' => 'SE', 'name' => 'السويد'],
            ['code' => 'CH', 'name' => 'سويسرا'],
            ['code' => 'SY', 'name' => 'سوريا'],
            ['code' => 'TW', 'name' => 'تايوان'],
            ['code' => 'TJ', 'name' => 'طاجكستان'],
            ['code' => 'TZ', 'name' => 'تانزانيا'],
            ['code' => 'TH', 'name' => 'تايلند'],
            ['code' => 'TL', 'name' => 'تيمور الشرقية'],
            ['code' => 'TG', 'name' => 'توجو'],
            ['code' => 'TK', 'name' => 'توكيلو'],
            ['code' => 'TO', 'name' => 'تونغا'],
            ['code' => 'TT', 'name' => 'ترينيداد وتوباغو'],
            ['code' => 'TN', 'name' => 'تونس'],
            ['code' => 'TR', 'name' => 'تركيا'],
            ['code' => 'TM', 'name' => 'تركمانستان'],
            ['code' => 'TC', 'name' => 'جزر الترك وجايكوس'],
            ['code' => 'TV', 'name' => 'توفالو'],
            ['code' => 'UG', 'name' => 'أوغندا'],
            ['code' => 'UA', 'name' => 'أوكرانيا'],
            ['code' => 'AE', 'name' => 'الإمارات العربية المتحدة'],
            ['code' => 'GB', 'name' => 'المملكة المتحدة'],
            ['code' => 'US', 'name' => 'الولايات المتحدة'],
            ['code' => 'UM', 'name' => 'جزر الولايات المتحدة البعيدة الصغيرة'],
            ['code' => 'UY', 'name' => 'أورغواي'],
            ['code' => 'UZ', 'name' => 'أوزبكستان'],
            ['code' => 'VU', 'name' => 'فانواتو'],
            ['code' => 'VE', 'name' => 'فنزويلا'],
            ['code' => 'VN', 'name' => 'فيتنام'],
            ['code' => 'VG', 'name' => 'جزر فرجين البريطانية'],
            ['code' => 'VI', 'name' => 'جزر فرجين الأمريكية'],
            ['code' => 'WF', 'name' => 'جزر والس وفوتونا'],
            ['code' => 'EH', 'name' => 'الصحراء الغربية'],
            ['code' => 'YE', 'name' => 'اليمن'],
            ['code' => 'ZM', 'name' => 'زامبيا'],
            ['code' => 'ZW', 'name' => 'زيمبابوي'],
            ['code' => 'AF', 'name' => 'أفغانستان'],
            ['code' => 'XK', 'name' => 'كوسوفو']
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
